# Exercise 5 

#### Names:
    Iftikhar Amiri iftikhar.amiri@nmbu.no
    Frederic Ljosland Strand frederic.ljosland.strand@nmbu.no

### Task 0: warmup

In this exercise, you will implement two functions that perform vector addition. A vector can be represented as a list of numbers in Python (e.g., [1, 2, 3]).

1. Define a function called inplace_add_vectors(vec1, vec2):

* This function should add the corresponding elements of vec2 to vec1.
* After calling this function, vec1 should be modified to hold the sum of the two vectors.
* Example:
    - v1 = [1, 2, 3]
    - v2 = [4, 5, 6]
    - inplace_add_vectors(v1, v2)
    - print(v1) # Output: [5, 7, 9]

2. Define a function called add_vectors(vec1, vec2):
* This function should return a new vector where each element is the sum of the corresponding elements from vec1 and vec2.
* The input vectors (vec1 and vec2) should remain unchanged.
* Example:
    - v1 = [1, 2, 3]
    - v2 = [4, 5, 6]
    - v3 = add_vectors(v1, v2)
    - print(v1) # Output: [1, 2, 3]
    - print(v3) # Output: [5, 7, 9]
    
If you want to check your solution or need help, take a look at this video.

In [2]:
def inplace_add_vectors(vec1: list, vec2: list) -> list:
    vec3 = []
    if len(vec1) == len(vec2):
        for _ in range(len(vec1)):
            vec1[_] = (vec1[_] + vec2[_])
    else:
        print('The vectors need to be the same size')

    return vec1

v1 = [1, 2, 3]
v2 = [4, 5, 6]

print(f'Vector 1 before operation: {v1}')
print(f'Inplace sum of v1 and v2: {inplace_add_vectors(v1, v2)}')
print(f'Vector 1 after operation: {v1}')

Vector 1 before operation: [1, 2, 3]
Inplace sum of v1 and v2: [5, 7, 9]
Vector 1 after operation: [5, 7, 9]


In [3]:
def add_vectors(vec1: list, vec2: list) -> list:
    vec3 = []
    if len(vec1) == len(vec2):
        for _ in range(len(vec1)):
            vec3.append(vec1[_] + vec2[_])
    else:
        print('The vectors need to be the same size')

    return vec3

v1 = [1, 2, 3]
v2 = [4, 5, 6]
print(f'Sum of v1 and v2: {add_vectors(v1, v2)}')

Sum of v1 and v2: [5, 7, 9]


### Task 1: Matrix operations

* Create a large matrix:
    - Make a 2D NumPy array of size , filled with random integers between 0 and 100.
* Write four functions to work with the matrix:
    - Mean function: Write a function that calculates the average (mean ) of all the numbers in the matrix. (Hint: The mean is the sum of all array entries divided by the total number of entries.)
    - Variance function: Write a function to calculate the variance of the matrix. (Hint: The variance measures how much the entries in the matrix differ from the mean. It's calculated as the average of the squared differences from the mean, i.e.,  where  and  are the array entries (or matrix entries).)
    - Sum function: Write a function that returns the total sum of all numbers in the matrix.
    - Multiply function: Write a function that returns a new matrix where each number in the input matrix is multiplied by a given number.

* Important Notes:
    - The input matrix should not be changed.
    - Be efficient in your implementation to avoid slowing down the program (for example, avoid unnecessary memory use or operations that slow down access to the matrix. Use concepts discussed in the lecture.)
    - Write the code for these functions yourself—don’t use built-in functions from libraries for the calculations.

In [4]:
%%time 

import numpy as np
import copy

N = 5000
matrix = np.random.randint(1, 100, size=(N,N))

def sum_matrix(matrix:list) -> int:
    total_sum = 0
    total_sum = sum(element for row in matrix for element in row)

    return total_sum

def mean_matrix(matrix:list) -> float:
    total_elements = matrix.shape[0] * matrix.shape[1]
    total_sum = sum_matrix(matrix)

    return total_sum / total_elements

def variance(matrix:list) -> float:
    total_var = 0
    matrix_mean = mean_matrix(matrix)
    total_var = sum((matrix_mean - element)**2 for row in matrix for element in row)
    variance = total_var / N**2

    return variance

def multiply(matrix: list, factor: int) -> list:
    new_matrix = copy.deepcopy(matrix)
    for i in range(len(new_matrix)):
        for j in range(len(matrix[i])):
            new_matrix[i][j] *= factor

    return new_matrix

print('-'*50)
print(f'Sum: {sum_matrix(matrix)}')
print(f'Mean: {mean_matrix(matrix)}')
print(f'Variance: {variance(matrix)}')
print('-'*50)
print(f'New matrix: {multiply(matrix,5) }')
print('-'*50)


--------------------------------------------------
Sum: 1249688539
Mean: 49.98754156
Variance: 816.5628072260062
--------------------------------------------------
New matrix: [[470  75 370 ... 200 275 455]
 [480 285 275 ... 150 140  55]
 [365 200 295 ... 430  60  45]
 ...
 [210 345 130 ... 275 290 285]
 [410  70 140 ... 110  60 455]
 [ 10 215 150 ... 475 190 245]]
--------------------------------------------------
CPU times: user 11.3 s, sys: 2.01 s, total: 13.4 s
Wall time: 11.2 s


### Task 2: Stencil matrix

Create a stencil matrix of the form with 50 by 50 entries. That is, create a matrix with diagonal entries of -2 and off-diagonal entries (the entries left and right of the diagonal) of 1. The first row is , i.e., the left off-diagonal entry is missing. The last row is , i.e., the right off-diagonal entry is missing.

We now want to compute the dominant eigenvalue of this matrix. An eigenvalue tells you how a matrix will change certain vectors through multiplication. If you do not know what an eigenvalue is, that is no problem and this knowledge is not required to solve this task. If you wish to get a better understanding, you can watch this video Links to an external site. and the videos in this series, but this is really not required. To compute the dominant eigenvalue, take a random vector  with 50 entries and multiply it by , leading to . Set  and repeat the process. That is, with our new , compute , set  and proceed. You can use numpy functionality to compute multiplications and norms.  After 100 iterations, print out the value of  which approximates the dominant eigenvalue. Check the result by computing Lambda, V = np.linalg.eig(A) and inspecting the largest absolute value in Lambda.

In [15]:
def iteration(A, num_iteration=100):
    v = np.random.rand(A.shape[1])
  
    for _ in range(num_iteration):
        v_new = np.dot(A, v)
        norm_v_new = np.linalg.norm(v_new)
        
        v = v_new / norm_v_new  # Normalize the vector after each iteration
                
    # Calculate the dominant eigenvalue approximation after completing the iterations
    dominant_eigenvalue = np.abs(np.dot(v.T, np.dot(A, v))) / np.dot(v.T, v)
    return dominant_eigenvalue

print(f"Eigenvalue after 100 iterations: {iteration(A, 100)}")
      
eigenvalue, _ = np.linalg.eig(A)
dominant_eigenvalue_np = np.max(np.abs(eigenvalue))

print(f"Eigenvalue from np: {dominant_eigenvalue_np}")

Eigenvalue after 100 iterations: 3.9822172343666913
Eigenvalue from np: 3.9962066574740853


### Task 3: challenge exercise

Try to rewrite task 2 so that you never have to store the matrix . For this, write your own function multiply_efficient(v), which computes the matrix-vector product without requiring the matrix. To write this function, think about the operations that will be performed when computing  and check if some of these operations can be left out for our choice of . Hint: A lot of entries in  are zero!

In [6]:
%%time

def multiply_efficient(v):
    N = len(v)
    result = np.zeros(N)
    
    for i in range(N):
        result[i] = -2 * v[i]
        if i > 0:
            result[i] += v[i - 1]
        if i < N - 1:
            result[i] += v[i + 1]
    
    return result

def multiplication_and_norm_efficient(vec):
    vec = multiply_efficient(vec)
    norm = np.linalg.norm(vec)
    vec = vec / norm

    return vec, norm

N = 50
vec = np.random.rand(N)

for _ in range(100):
    vec, dominant_eigenvalue_approx = multiplication_and_norm_efficient(vec)

print(f"Approximated dominant eigenvalue: {dominant_eigenvalue_approx}")

A = np.zeros((N, N))
for i in range(N):
    A[i, i] = -2
    if i > 0:
        A[i, i - 1] = 1
    if i < N - 1:
        A[i, i + 1] = 1

eigenvalues, _ = np.linalg.eig(A)
true_dominant_eigenvalue = np.max(np.abs(eigenvalues))

print(f"True dominant eigenvalue: {true_dominant_eigenvalue}")


Approximated dominant eigenvalue: 3.9930095634831435
True dominant eigenvalue: 3.9962066574740853
CPU times: user 2.89 ms, sys: 926 µs, total: 3.81 ms
Wall time: 2.89 ms
