# Exercise 5 

#### Names:
    Iftikhar Amiri iftikhar.amiri@nmbu.no
    Frederic Ljosland Strand frederic.ljosland.strand@nmbu.no

### Task 0: warmup

In this exercise, you will implement two functions that perform vector addition. A vector can be represented as a list of numbers in Python (e.g., [1, 2, 3]).

1. Define a function called inplace_add_vectors(vec1, vec2):

* This function should add the corresponding elements of vec2 to vec1.
* After calling this function, vec1 should be modified to hold the sum of the two vectors.
* Example:
    - v1 = [1, 2, 3]
    - v2 = [4, 5, 6]
    - inplace_add_vectors(v1, v2)
    - print(v1) # Output: [5, 7, 9]

2. Define a function called add_vectors(vec1, vec2):
* This function should return a new vector where each element is the sum of the corresponding elements from vec1 and vec2.
* The input vectors (vec1 and vec2) should remain unchanged.
* Example:
    - v1 = [1, 2, 3]
    - v2 = [4, 5, 6]
    - v3 = add_vectors(v1, v2)
    - print(v1) # Output: [1, 2, 3]
    - print(v3) # Output: [5, 7, 9]
    
If you want to check your solution or need help, take a look at this video.

In [8]:
def inplace_add_vectors(vec1: list, vec2: list) -> list:
    vec3 = []
    if len(vec1) == len(vec2):
        for _ in range(len(vec1)):
            vec1[_] = (vec1[_] + vec2[_])
    else:
        print('The vectors need to be the same size')

    return vec1

v1 = [1, 2, 3]
v2 = [4, 5, 6]

print(f'Vector 1 before operation: {v1}')
print(f'Inplace sum of v1 and v2: {inplace_add_vectors(v1, v2)}')
print(f'Vector 1 after operation: {v1}')

Vector 1 before operation: [1, 2, 3]
Inplace sum of v1 and v2: [5, 7, 9]
Vector 1 after operation: [5, 7, 9]


In [1]:
def add_vectors(vec1: list, vec2: list) -> list:
    vec3 = []
    if len(vec1) == len(vec2):
        for _ in range(len(vec1)):
            vec3.append(vec1[_] + vec2[_])
    else:
        print('The vectors need to be the same size')

    return vec3

v1 = [1, 2, 3]
v2 = [4, 5, 6]
print(f'Sum of v1 and v2: {add_vectors(v1, v2)}')

Sum of v1 and v2: [5, 7, 9]


### Task 1: Matrix operations

* Create a large matrix:
    - Make a 2D NumPy array of size , filled with random integers between 0 and 100.
* Write four functions to work with the matrix:
    - Mean function: Write a function that calculates the average (mean ) of all the numbers in the matrix. (Hint: The mean is the sum of all array entries divided by the total number of entries.)
    - Variance function: Write a function to calculate the variance of the matrix. (Hint: The variance measures how much the entries in the matrix differ from the mean. It's calculated as the average of the squared differences from the mean, i.e.,  where  and  are the array entries (or matrix entries).)
    - Sum function: Write a function that returns the total sum of all numbers in the matrix.
    - Multiply function: Write a function that returns a new matrix where each number in the input matrix is multiplied by a given number.

* Important Notes:
    - The input matrix should not be changed.
    - Be efficient in your implementation to avoid slowing down the program (for example, avoid unnecessary memory use or operations that slow down access to the matrix. Use concepts discussed in the lecture.)
    - Write the code for these functions yourself—don’t use built-in functions from libraries for the calculations.

In [49]:
import numpy as np

N = 5000
matrix = np.random.randint(1, 100, size=(N,N))

def mean(matrix:list) -> int:
    total_sum = 0
    total_elements = 0

    for row in matrix:
        for element in row:
            total_sum += element
            total_elements += 1

    return total_sum / total_elements

def variance(matrix:list) -> int:
    total_var = 0
    for row in matrix:
        for element in row:
            total_var += (mean - element)**2
    variance = total_var / N**2

    return variance

def sum(matrix:list) -> int:
    total_sum = 0

    for row in matrix:
        for element in row:
            total_sum += element

    return total_sum

def multiply(matrix:list, factor:int) -> list:
    for row in matrix:
        for element in row:
            element * factor

    return matrix

mean = mean(matrix)
print(f'Mean: {mean}')
variance = variance(matrix)
print(f'Variance: {variance}')
total_sum = sum(matrix)
print(f'Sum: {total_sum}')
new_matrix = multiply(matrix,5) 
print(f'New matrix: {new_matrix}')

Mean: 49.99559416
Variance: 816.7565427434835
Sum: 1249889854
New matrix: [[57  2 95 ... 42 54 54]
 [61  9  4 ... 36 13 69]
 [89 88 60 ... 40 88 21]
 ...
 [ 4 99 29 ... 75  8 89]
 [77 54 16 ... 66 84 45]
 [ 8 47  4 ... 57 27 82]]


### Task 2: Stencil matrix

Create a stencil matrix of the form with 50 by 50 entries. That is, create a matrix with diagonal entries of -2 and off-diagonal entries (the entries left and right of the diagonal) of 1. The first row is , i.e., the left off-diagonal entry is missing. The last row is , i.e., the right off-diagonal entry is missing.

We now want to compute the dominant eigenvalue of this matrix. An eigenvalue tells you how a matrix will change certain vectors through multiplication. If you do not know what an eigenvalue is, that is no problem and this knowledge is not required to solve this task. If you wish to get a better understanding, you can watch this video Links to an external site. and the videos in this series, but this is really not required. To compute the dominant eigenvalue, take a random vector  with 50 entries and multiply it by , leading to . Set  and repeat the process. That is, with our new , compute , set  and proceed. You can use numpy functionality to compute multiplications and norms.  After 100 iterations, print out the value of  which approximates the dominant eigenvalue. Check the result by computing Lambda, V = np.linalg.eig(A) and inspecting the largest absolute value in Lambda.

In [47]:
def multiplication_and_norm(matrix, vec):
    vec = np.dot(matrix, vec)
    norm = np.linalg.norm(vec)
    vec = vec / norm

    return vec, norm

N = 50
A = np.zeros((N, N))

for i in range(N):
    A[i, i] = -2
    if i > 0:
        A[i, i - 1] = 1
    if i < N - 1:
        A[i, i + 1] = 1

vec = np.random.rand(N)

for _ in range(100):
    vec, dominant_eigenvalue_approx = multiplication_and_norm(A, vec)

print(f"Approximated dominant eigenvalue: {dominant_eigenvalue_approx}")

eigenvalues, _ = np.linalg.eig(A)
true_dominant_eigenvalue = np.max(np.abs(eigenvalues))

print(f"True dominant eigenvalue: {true_dominant_eigenvalue}")


Approximated dominant eigenvalue: 3.983399637485292
True dominant eigenvalue: 3.9962066574740853
CPU times: user 2.13 ms, sys: 1.85 ms, total: 3.98 ms
Wall time: 3.1 ms


### Task 3: challenge exercise

Try to rewrite task 2 so that you never have to store the matrix . For this, write your own function multiply_efficient(v), which computes the matrix-vector product without requiring the matrix. To write this function, think about the operations that will be performed when computing  and check if some of these operations can be left out for our choice of . Hint: A lot of entries in  are zero!